config/routes.rb
Rails.application.routes.draw do
  resources :nearest_stations
  resources :properties
  root "properties#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nearest_station.rb
class NearestStation < ApplicationRecord
  belongs_to :property,inverse_of: :nearest_stations
end

app/models/property.rb
class Property < ApplicationRecord
  has_many:nearest_stations, dependent: :destroy, inverse_of: :property
  accepts_nested_attributes_for :nearest_stations, allow_destroy:true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nearest_stations_controller.rb
class NearestStationsController < ApplicationController
  before_action :set_nearest_station, only: %i[ show edit update destroy ]

  
  def index
    @nearest_stations = NearestStation.all
  end

  def show
  end

  def new
    @nearest_station = NearestStation.new
  end

  def edit
  end

  def create
    @nearest_station = NearestStation.new(nearest_station_params)

    respond_to do |format|
      if @nearest_station.save
        format.html { redirect_to edit_property_path, notice: "Nearest station was successfully created." }
        format.json { render :show, status: :created, location: @nearest_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nearest_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @nearest_station.update(nearest_station_params)
        format.html { redirect_to @nearest_station, notice: "Nearest station was successfully updated." }
        format.json { render :show, status: :ok, location: @nearest_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nearest_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @nearest_station.destroy
    respond_to do |format|
      format.html { redirect_to nearest_stations_url, notice: "Nearest station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_nearest_station
      @nearest_station = NearestStation.find(params[:id])
    end

    def nearest_station_params
      params.require(:nearest_station).permit(:route, :station_name, :on_foot, :property_id)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  def index
    @properties = Property.all
  end

  def show
    @nearest_stations = @property.nearest_stations
  end

  def new
    @property = Property.new
    2.times { @property.nearest_stations.build}
  end

  def edit
    @nearest_station = @property.nearest_stations.build
  end

  def create
    @property = Property.new(property_params)
    
    respond_to do |format|
      if @property.save
        format.html { redirect_to properties_path, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to properties_path, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit(:property_name, :rent, :address, :age, :remark,nearest_stations_attributes: [:id,:route, :station_name, :on_foot, :property_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nearest_stations_helper.rb
module NearestStationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def converting_to_jpy(rent)
    "#{rent.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExamRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nearest_stations/_form.html.erb
<%= form_with(model: nearest_station, local: true) do |form| %>
  <% if nearest_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nearest_station.errors.count, "error") %> prohibited this nearest_station from being saved:</h2>

      <ul>
        <% nearest_station.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :路線名 %>
    <%= form.text_field :route %>
  </div>

  <div class="field">
    <%= form.label :駅名 %>
    <%= form.text_field :station_name %>
  </div>

  <div class="field">
    <%= form.label :徒歩分数 %>
    <%= form.text_field :on_foot %>分
  </div>

  <div class="actions">
    <%= form.submit'登録する' %>
  </div>
<% end %>

app/views/nearest_stations/edit.html.erb
<h1>最寄駅編集</h1>

<%= render 'form', nearest_station: @nearest_station %>

<%= link_to '詳細', @nearest_station %> |
<%= link_to '戻る', nearest_stations_path %>

app/views/nearest_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>最寄駅一覧</h1>

<table>
  <thead>
    <tr>
      <th>路線名</th>
      <th>駅名</th>
      <th>徒歩分数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nearest_stations.each do |nearest_station| %>
      <tr>
        <td><%= nearest_station.route %></td>
        <td><%= nearest_station.station_name %></td>
        <td><%= nearest_station.on_foot %></td>
        <td><%= link_to '詳細', nearest_station %></td>
        <td><%= link_to '編集', edit_nearest_station_path(nearest_station) %></td>
        <td><%= link_to '削除', nearest_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nearest Station', new_nearest_station_path %>

app/views/nearest_stations/new.html.erb
<h1>最寄り駅</h1>

<%= render 'form', nearest_station: @nearest_station %>

<%= link_to '戻る', nearest_stations_path %>

app/views/nearest_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>路線名:</strong>
  <%= @nearest_station.route %>
</p>

<p>
  <strong>駅名:</strong>
  <%= @nearest_station.station_name %>
</p>

<p>
  <strong>徒歩分数:</strong>
  <%= @nearest_station.on_foot %>
</p>

<%= link_to '編集', edit_nearest_station_path(@nearest_station) %> |
<%= link_to '戻る', nearest_stations_path %>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :物件名 %>
    <%= form.text_field :property_name %>
  </div>

  <div class="field">
    <%= form.label :賃料 %>
    <%=  form.text_field :rent %>円
  </div>

  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :築年数 %>
    <%= form.text_field :age %>年
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :remark %>
  </div>

  <hr width=auto>
<% n = 0 %>
<%= form.fields_for :nearest_stations do | nearest_station | %>

<h3>最寄り駅<%= n += 1 %></h3>

    <div class="route">
      <%= form.label :路線名 %>
      <%= nearest_station.text_field :route %>
    </div>

    <div class="station_name">
      <%= form.label :駅名 %>
      <%= nearest_station.text_field :station_name %>
    </div>

    <div class="on_foot">
      <%= form.label :徒歩分数 %>
      <%= nearest_station.text_field :on_foot %>分
    </div>

    <% end %>

    <%= form.submit '登録する' %>
  <% end %>

app/views/properties/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', property: @property %>

<%= link_to '詳細', @property %> |
<%= link_to '戻る', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th>最寄り駅数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_name %></td>
        <td><%= converting_to_jpy(property.rent) %>円</td>
        <td><%= property.address %></td>
        <td><%= property.age %>年</td>
        <td><%= property.remark %></td>
        <td><%= property.nearest_stations.length %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_property_path %>

app/views/properties/new.html.erb
<h1>物件登録</h1>

<%= render 'form', property: @property %>

<%= link_to '戻る', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>物件名:</strong>
  <%= @property.property_name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @property.rent %>円
</p>

<p>
  <strong>住所:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @property.age %>年
</p>

<p>
  <strong>備考:</strong>
  <%= @property.remark %>
</p>

<% n = 0 %>
<% @nearest_stations.each do | nearest_station | %>
  <% if @property.nearest_stations.any? %>

  <h3>最寄り駅<%= n += 1 %></h3>
  
      <div class="route">
        <strong>路線名</strong>
        <%= nearest_station.route %>
      </div><br>
  
      <div class="station_name">
        <strong>駅名</strong>
        <%= nearest_station.station_name %>
      </div><br>
  
      <div class="on_foot">
      <strong>徒歩分数</strong>
        <%= nearest_station.on_foot %>分
      </div><br>
  
    <% end %>
  <% end %>
<%= link_to '編集', edit_property_path(@property) %> |
<%= link_to '戻る', properties_path %>